apiVersion: v1
kind: Service
metadata:
  name: distributed-step-service
spec:
  selector:
    app: distributed-step
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}