apiVersion: v1
kind: Service
metadata:
  name: boss-service
spec:
  type: NodePort
  selector:
    app: boss
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}