apiVersion: v1
kind: Service
metadata:
  name: operation-group-service
spec:
  selector:
    app: operation-group
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}