{{ if .Values.role.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.role.name }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
roleRef:
  kind: Role
  name: container-service-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}