apiVersion: v1
kind: Service
metadata:
  name: container-service
spec:
  selector:
    app: container-service
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}