name: Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Check things
      run: ls
      working-directory: ./Tests
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./Tests
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./Tests
